const carData = [
  {
    id: 1,
    carId: 1,
    name: "TATA",
    model: "Nexon EV",
    type: "Electric",
    year: 2023,
    rating: 4.5,
    passengers: 4,
    transmission: "Automatic",
    price: {
      min_price: "12.49",
      max_price: "17.19",
    },
    range: 453,
    battery: 46.08,
    power: 148,
    charging: {
      min_time: 6.5,
      max_time: 9.17,
    },
    bodyStyle: "SUV",
    warranty_years: 3,
    warranty_km: 125000,
    length: 3993,
    width: 1811,
    height: {
      min_height: 1606,
      max_height: 1616,
    },
    weight: 1400,
    cargoVolume: 350,
    about:
      "The TATA Nexon EV is a sub-4 metre electric SUV that has been extremely popular in the Indian market. It first went on sale in 2020 and later down line, got a heavily revised facelift in 2023. The Nexon EV brings power, silence and lower running costs to what is an already capable car in its ICE avatar.",
    image: 
    "/images/BuyCars/newtnexcar1.png",
    //  "https://firebasestorage.googleapis.com/v0/b/zymo-prod.appspot.com/o/carImage%2FNexon%20EV.jpeg?alt=media&token=f21e99fb-44f0-48b4-9781-212c197fd1b5",
    monthlyTestDriveFee: 52500,
    securityDeposit: 40000,
    totalAmount: 92500,
    freeKilometers: 1500,
    vendor: "MyChoize",
  },
  {
    id: 2,
    carId: 2,
    name: "Volvo",
    model: "XC40 Recharge",
    type: "Electric",
    year: 2023,
    rating: 4.9,
    passengers: 5,
    transmission: "Automatic",
    price: {
      min_price: "54.00",
      max_price: "56.00",
    },
    range: 418,
    battery: 78,
    power: 408,
    charging: {
      min_time: 6.5,
      max_time: 8.0,
    },
    bodyStyle: "SUV",
    warranty_years: 3,
    warranty_km: 100000,
    length: 4425,
    width: 1863,
    height: {
      min_height: 1650,
      max_height: 1652,
    },
    weight: 2150,
    cargoVolume: 452,
    about:
      "The Volvo XC40 Recharge is a luxury electric SUV offering powerful dual-motor performance, refined comfort, and a premium safety package. Perfect for those looking for sophistication and sustainability.",
      image:"/images/BuyCars/xc40img1.png",
    monthlyTestDriveFee: 10000,
    securityDeposit: 50000,
    totalAmount: 60000,
    freeKilometers: 2000,
    vendor: "Volvo India",
  },
  {
    id: 3,
    carId: 3,
    name: "TATA",
    model: "Curvv EV",
    type: "Electric",
    year: 2024,
    rating: 4.6,
    passengers: 5,
    transmission: "Automatic",
    price: {
      min_price: "18.00",
      max_price: "22.00",
    },
    range: 500,
    battery: 50,
    power: 170,
    charging: {
      min_time: 6.5,
      max_time: 7.5,
    },
    bodyStyle: "Coupe SUV",
    warranty_years: 8,
    warranty_km: 160000,
    length: 4300,
    width: 1850,
    height: {
      min_height: 1600,
      max_height: 1610,
    },
    weight: 1600,
    cargoVolume: 400,
    about:
      "The Tata Curvv EV is a futuristic coupe-style electric SUV, combining modern design with a long range. It represents Tata's vision of bold and smart EVs for the next generation.",
    image:"/images/BuyCars/tatacurvvimg1.png",
    monthlyTestDriveFee: 6000,
    securityDeposit: 20000,
    totalAmount: 26000,
    freeKilometers: 1500,
    vendor: "TATA",
  },
  {
    id: 4,
    carId: 4,
    name: "Hyundai",
    model: "Kona Electric",
    type: "Electric",
    year: 2023,
    rating: 4.7,
    passengers: 5,
    transmission: "Automatic",
    price: {
      min_price: "23.00",
      max_price: "25.00",
    },
    range: 452,
    battery: 39.2,
    power: 136,
    charging: {
      min_time: 6.1,
      max_time: 7.5,
    },
    bodyStyle: "SUV",
    warranty_years: 8,
    warranty_km: 160000,
    length: 4180,
    width: 1800,
    height: {
      min_height: 1570,
      max_height: 1580,
    },
    weight: 1535,
    cargoVolume: 332,
    about:
      "The Hyundai Kona Electric is a stylish and efficient SUV with a solid range and advanced features. A great blend of urban performance and eco-conscious driving.",
    image:"/images/BuyCars/konaimg1.png",
    monthlyTestDriveFee: 7000,
    securityDeposit: 25000,
    totalAmount: 32000,
    freeKilometers: 1600,
    vendor: "Hyundai",
  },
];

export default carData;
